### ISSUE TITLE
MVP REQ: Click on an attraction and display the description.

### ISSUE THREAD

**Issue by tedpennington** [nss-day-cohort-19/d19-group-theme-park-park-rangers#10]

**Comment by tedpennington** [comment]
Working in Park Area boxes.  MVP Req isn't clear as to whether this is also required in attraction category lists though (exact verbiage of bullet point is simply: "Click on an attraction and display the description."), so not sure.  UX considerations would probably be for this to be desirable but let's discuss what's possible in time remaining.

**Comment by ghost** [comment]
We've got it all displaying for just in case

**Comment by tedpennington** [comment]
👍
