### ISSUE TITLE
MVP REQ: Each area will have a minimum of 8 attractions.

### ISSUE THREAD

**Issue by tedpennington** [nss-day-cohort-19/d19-group-theme-park-park-rangers#11]

**Comment by tedpennington** [comment]
Cinderella Castle area currently only shows 1 attraction.

**Comment by ghost** [comment]
This is actually correct. Looks like Greg only entered 1 attraction that also matches the attraction_type ID and area ID. I thought it was weird too but it is right :D

**Comment by tedpennington** [comment]
Ok, yeah I saw the same in the Json. Wasn't sure if we were expected to create more but I think since the functionality is there to display them if they existed we're good.
